name: Release Publish Artifacts
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  release-publish-artifacts:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v4
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Install Dagger
        env:
          # renovate: datasource=github-tags depName=dagger/dagger versioning=semver
          DAGGER_VERSION: 0.20.1
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
      - name: Create image and manifest
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.REPO_PAT }}
        run: |
          task publish
          task manifest
      - name: Attach manifest to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          task upload-manifest-to-release
